### ISSUE TITLE
lxd=lx1 for turbChannel example?

### ISSUE THREAD

**Issue by fischer1** [Nek5000/NekExamples#101]
Why is dealiasing turned off for the turbChannel example?

lxd=lx1=8 ??

**Comment by stgeke** [comment]
In guess because it’s an LES and you don’t need it as you filter already.  

On 9 Feb 2018, at 02:08, fischer1 <notifications@github.com <mailto:notifications@github.com> > wrote:

Why is dealiasing turned off for the turbChannel example?

lxd=lx1=8 ??

**Comment by fischer1** [comment]
Thanks!
I was thinking that might be the rationale, but I would normally still dealias?

**Comment by stgeke** [comment]
Why?

On 9 Feb 2018, at 13:08, fischer1 <notifications@github.com <mailto:notifications@github.com> > wrote:

Thanks!
I was thinking that might be the rationale, but I would normally still dealias?

**Comment by fischer1** [comment]
Dealiasing simply ensures that there are no spurious eigenvalues in the right half of the complex plane.

I guess your point is that the eddy viscosity stabilizes and therefore we don't need the overhead of dealiasing?

**Comment by stgeke** [comment]
Yes the filtering stabilizes already so why wasting computational time with dealiasing. That was at least my rational. 

On 9 Feb 2018, at 14:00, fischer1 <notifications@github.com <mailto:notifications@github.com> > wrote:

Dealiasing simply ensures that there are no spurious eigenvalues in the right half of the complex plane.

I guess your point is that the eddy viscosity stabilizes and therefore we don't need the overhead of dealiasing?

**Comment by fischer1** [comment]
OK!

It's the VLN way :)

(My only worry - when people start using that example as a starting point and find that dealiasing makes a difference ?)

**Comment by pschlatt1** [comment]
Just as a comment: Dealiasing might not only be about stability, but also accuracy. Indeed, filtering kills some of the most badly aliased modes, but of course not all aliasing errors. As these are clearly errors of the quadrature, I would argue that one should correct them in any case.

**Comment by pschlatt1** [comment]
(there is the instructive figure in the old Canuto book about it)

**Comment by stgeke** [comment]
Are these errors important in an LES?

On 9 Feb 2018, at 15:15, Philipp Schlatter <notifications@github.com <mailto:notifications@github.com> > wrote:

Just as a comment: Dealiasing might not only be about stability, but also accuracy. Indeed, filtering kills some of the most badly aliased modes, but of course not all aliasing errors. As these are clearly errors of the quadrature, I would argue that one should correct them in any case.

**Comment by stgeke** [comment]
I think we should set lxd=12 and turn on/off dealiasing in the par file. This way it’s obvious for the user. To make this happen we need to support OIFS w/o dealiasing.

On 9 Feb 2018, at 16:33, Stefan K. <notifications@github.com <mailto:notifications@github.com> > wrote:

Are these errors important in an LES?

On 9 Feb 2018, at 15:15, Philipp Schlatter <notifications@github.com <mailto:notifications@github.com> <mailto:notifications@github.com <mailto:notifications@github.com> > > wrote:

Just as a comment: Dealiasing might not only be about stability, but also accuracy. Indeed, filtering kills some of the most badly aliased modes, but of course not all aliasing errors. As these are clearly errors of the quadrature, I would argue that one should correct them in any case.

**Comment by pschlatt1** [comment]
I think these errors can be important, potentially even more important in LES than DNS as we have more energy in the higher modes because of the lower resolution.

**Comment by emerzari** [comment]
I like the this option "set lxd=12 and turn on/off dealiasing in the par file."


Dealiasing is definitely a best practice, but the user may want to run fast first and it is a good standard setup for LES.


Perhaps adding a comment would also help.


________________________________

**Comment by fischer1** [comment]
Unless the user is also running characteristics, the overhead of dealiasing is nil.

**Comment by stgeke** [comment]
Enabled dealiasing by default. See https://github.com/Nek5000/NekExamples/commit/1a5387cc5a241a24e994823cabdf324856df4b2c
