### ISSUE TITLE
Turb Channel must go

### ISSUE THREAD

**Issue by fischer1** [Nek5000/NekExamples#105]
We need to update / replace turbchannel.

1.  It uses a dynamic Smagorinsky model that I coded up but never fully validated. (It's original intent was to show developers how they might go about implementing such a model, rather than to be viewed as a validated SGS model.  With our current and future user base, that usage model is not appropriate.)

2. It uses an ad-hoc forcing function, rather than fixed flow-rate, which is the preferred forcing for channel flow.

3. I'm certain there are other issues as well...

**Comment by pschlatt1** [comment]
I would suggest to have a turbulent channel example, e.g. reproducing the smallest Moser-Kim-Mansour case, together with proper initialisation, forcing and calculation of some (low-order) statistics. Channel is still the most popular test case in (fundamental) CFD.

**Comment by fischer1** [comment]
Absolutely.

I definitely want a channel case --- just not the one we have :)

**Comment by stgeke** [comment]
The current turbChannel is using filtering + constant mass flux. So what you're suggesting is to delete the Smagorinski stuff which is still in the usr file. Right?

-----Original message-----

**Comment by fischer1** [comment]
I think a general clean-up is in order.

It also uses the adhoc forcing, which is not good (again, my coding back in the day when I didn't have a clean fixed-mass-flowrate in place).

When I look in the example I see ffx = fxx_new ;  which is not constant mass flux?

(Constant mass flux is implemented via p54/p55.)

**Comment by stgeke** [comment]
The current example is _not_ using userf(). Instead it is using p54/p55.

-----Original message-----

**Comment by fischer1** [comment]
Sigh...

I guess I'm looking at the tarball --- i.e., I'm viewing it from the users' perspective.

??

**Comment by stgeke** [comment]
Yes I am also looking at the v17.0 tarball like a user. 
Anyway I will clean it up. 

-----Original message-----

**Comment by stgeke** [comment]
Ok I just updated the example. Feel free to reopen this issue if you are still not happy.
