### ISSUE TITLE
turbChannel in NekExamples doesn't find avs.f 

### ISSUE THREAD

**Issue by slopezcastano** [Nek5000/NekExamples#109]
Hi All
    I've been trying to run turbChannel example in NEK5000 without success. It seems the subroutine avs is missing from the repo. I get the following error after I execute $> python -m 'unittest' NekTests.TurbChannel.test_PnPn_Parallel

```
mpif77 -c  -O2 -std=legacy -fdefault-real-8 -fdefault-double-8 -cpp -DMPI -DUNDERSCORE -DTIMER -I/home/scastano/Nek5000/NekExamples/turbChannel -I/home/scastano/Nek5000/core -I./ /home/scastano/Nek5000/NekExamples/turbChannel/turbChannel.f  -o obj/turbChannel.o 
/home/scastano/Nek5000/NekExamples/turbChannel/turbChannel.f:227:48:

             call planar_avg(wo1      ,ravg(1,i),igs_x)
                                                1
Warning: Type mismatch in argument ‘hndl’ at (1); passed INTEGER(4) to REAL(8)
/home/scastano/Nek5000/NekExamples/turbChannel/turbChannel.f:228:48:

             call planar_avg(stat(1,i),wo1      ,igs_z)
                                                1
Warning: Type mismatch in argument ‘hndl’ at (1); passed INTEGER(4) to REAL(8)
mpif77  -O2 -std=legacy -fdefault-real-8 -fdefault-double-8 -cpp -DMPI -DUNDERSCORE -DTIMER -I/home/scastano/Nek5000/NekExamples/turbChannel -I/home/scastano/Nek5000/core -I./ -o nek5000 obj/turbChannel.o obj/drive.o obj/drive1.o obj/drive2.o obj/plan5.o obj/plan4.o obj/bdry.o obj/coef.o obj/conduct.o obj/connect1.o obj/connect2.o obj/dssum.o obj/edgec.o obj/eigsolv.o obj/gauss.o obj/genxyz.o obj/navier1.o obj/makeq.o obj/navier0.o obj/navier2.o obj/navier3.o obj/navier4.o obj/prepost.o obj/speclib.o obj/map2.o obj/mvmesh.o obj/ic.o obj/gfldr.o obj/ssolv.o obj/planx.o obj/math.o obj/mxm_wrapper.o obj/hmholtz.o obj/gfdm_par.o obj/gfdm_op.o obj/gfdm_solve.o obj/subs1.o obj/subs2.o obj/genbox.o obj/gmres.o obj/hsmg.o obj/convect.o obj/induct.o obj/perturb.o obj/navier5.o obj/navier6.o obj/navier7.o obj/navier8.o obj/fast3d.o obj/fasts.o obj/calcz.o obj/byte.o obj/chelpers.o obj/byte_mpi.o obj/postpro.o obj/dprocmap.o obj/interp.o obj/intp_usr.o obj/cvode_driver.o obj/nek_comm.o obj/multimesh.o obj/vprops.o obj/makeq_aux.o obj/papi.o obj/nek_in_situ.o obj/reader_rea.o obj/reader_par.o obj/reader_re2.o obj/finiparser.o obj/iniparser.o obj/dictionary.o obj/hpf.o obj/mxm_std.o obj/comm_mpi.o obj/blas.o obj/dsygv.o -L/home/scastano/Nek5000/3rd_party/gslib/lib -lgs 
obj/turbChannel.o: In function `uservp_':
turbChannel.f:(.text+0x2b6): undefined reference to `avs_vdiff_'
obj/turbChannel.o: In function `userchk_':
turbChannel.f:(.text+0x5a4): undefined reference to `intp_nfld_'
turbChannel.f:(.text+0x5fb): undefined reference to `intp_nfld_'
turbChannel.f:(.text+0x6c7): undefined reference to `intp_nfld_'
collect2: error: ld returned 1 exit status
```

Note that I had to change also the 'userchk' subroutine due to a repeated COMMON declaration:
```

c      common /ctorq/  dragx(0:maxobj),dragpx(0:maxobj),dragvx(0:maxobj)
c     $             , dragy(0:maxobj),dragpy(0:maxobj),dragvy(0:maxobj)
c     $             , dragz(0:maxobj),dragpz(0:maxobj),dragvz(0:maxobj)
c
c     $             , torqx(0:maxobj),torqpx(0:maxobj),torqvx(0:maxobj)
c     $             , torqy(0:maxobj),torqpy(0:maxobj),torqvy(0:maxobj)
c     $             , torqz(0:maxobj),torqpz(0:maxobj),torqvz(0:maxobj)
c
c     $             , dpdx_mean,dpdy_mean,dpdz_mean
c     $             , dgtq(3,4)

      save dragx_avg
```

Any help regarding the avs subroutines is deeply appreciated.

**Comment by stgeke** [comment]
Is there any good reason not to use the official release (v17.0)? You picked up the latest master on NekExamples which needs to be synced with the latest master on Nek5000. That's something we haven't done yet. 

Stefan

-----Original message-----
> From:slopezcastano <notifications@github.com>
> Sent: Tuesday 19th June 2018 16:54
> To: Nek5000/NekExamples <NekExamples@noreply.github.com>
> Cc: Subscribed <subscribed@noreply.github.com>
> Subject: [Nek5000/NekExamples] turbChannel in NekExamples doesn't find avs.f (#109)
> 
> Hi All
> I've been trying to run turbChannel example in NEK5000 without success. It seems the subroutine avs is missing from the repo. I get the following error after I execute $> python -m 'unittest' NekTests.TurbChannel.test_PnPn_Parallel
> mpif77 -c  -O2 -std=legacy -fdefault-real-8 -fdefault-double-8 -cpp -DMPI -DUNDERSCORE -DTIMER -I/home/scastano/Nek5000/NekExamples/turbChannel -I/home/scastano/Nek5000/core -I./ /home/scastano/Nek5000/NekExamples/turbChannel/turbChannel.f  -o obj/turbChannel.o 
> /home/scastano/Nek5000/NekExamples/turbChannel/turbChannel.f:227:48:
>              call planar_avg(wo1      ,ravg(1,i),igs_x)
>                                                 1
> Warning: Type mismatch in argument ‘hndl’ at (1); passed INTEGER(4) to REAL(8)
> /home/scastano/Nek5000/NekExamples/turbChannel/turbChannel.f:228:48:
>              call planar_avg(stat(1,i),wo1      ,igs_z)
>                                                 1
> Warning: Type mismatch in argument ‘hndl’ at (1); passed INTEGER(4) to REAL(8)
> mpif77  -O2 -std=legacy -fdefault-real-8 -fdefault-double-8 -cpp -DMPI -DUNDERSCORE -DTIMER -I/home/scastano/Nek5000/NekExamples/turbChannel -I/home/scastano/Nek5000/core -I./ -o nek5000 obj/turbChannel.o obj/drive.o obj/drive1.o obj/drive2.o obj/plan5.o obj/plan4.o obj/bdry.o obj/coef.o obj/conduct.o obj/connect1.o obj/connect2.o obj/dssum.o obj/edgec.o obj/eigsolv.o obj/gauss.o obj/genxyz.o obj/navier1.o obj/makeq.o obj/navier0.o obj/navier2.o obj/navier3.o obj/navier4.o obj/prepost.o obj/speclib.o obj/map2.o obj/mvmesh.o obj/ic.o obj/gfldr.o obj/ssolv.o obj/planx.o obj/math.o obj/mxm_wrapper.o obj/hmholtz.o obj/gfdm_par.o obj/gfdm_op.o obj/gfdm_solve.o obj/subs1.o obj/subs2.o obj/genbox.o obj/gmres.o obj/hsmg.o obj/convect.o obj/induct.o obj/perturb.o obj/navier5.o obj/navier6.o obj/navier7.o obj/navier8.o obj/fast3d.o obj/fasts.o obj/calcz.o obj/byte.o obj/chelpers.o obj/byte_mpi.o obj/postpro.o obj/dprocmap.o obj/interp.o obj/intp_usr.o obj/cvode_driver.o obj/nek_comm.o obj/
 multimesh.o obj/vprops.o obj/makeq_aux.o obj/papi.o obj/nek_in_situ.o obj/reader_rea.o obj/reader_par.o obj/reader_re2.o obj/finiparser.o obj/iniparser.o obj/dictionary.o obj/hpf.o obj/mxm_std.o obj/comm_mpi.o obj/blas.o obj/dsygv.o -L/home/scastano/Nek5000/3rd_party/gslib/lib -lgs

**Comment by slopezcastano** [comment]
Not really, I just cloned the repo directly from the github site. I guess you tell me to download a tarball directly from the site. Am I correct?

**Comment by stgeke** [comment]
Correct, see also FAQ.

-----Original message-----

**Comment by slopezcastano** [comment]
My bad! Indeed was written there. Thanks anyway.
