### ISSUE TITLE
[RANS] copy pr to prlag would change the scheme when PNPN-2 + p27=3

### ISSUE THREAD

**Issue by yslan** [Nek5000/NekExamples#113]
https://github.com/Nek5000/NekExamples/blob/a545a144dfb7cc90a78b896a2254a5d14a8c5641/RANSChannel/RANSchan.usr#L536

I know that PNPN scheme doesn't do extrapolation, so when monitoring the difference between previous step, we need to copy prlag=pr manually. 

However, PNPN-2 scheme will do extrapolation if p27=3 (plan3 > cresvif > extrapp). And the copy at here will break the timing of the extrapolation and the "16-digit-matched-perfect-fullrestart".
We need a if-statement to avoid that, or use local saved array other than prlag.

**Comment by dshaver-ANL** [comment]
A local array is a quick fix for the issue.  A better one would be to have the pressure properly lagged for all schemes so we don't have to worry about it here.

**Comment by stgeke** [comment]
Ok let me think about this. I think you're right we should just fill prlag no matter what.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/NekExamples/commit/a611f18a140cdf4dc9a7abb8a5736ab6c017ca48
