### ISSUE TITLE
turbPipe not compiling

### ISSUE THREAD

**Issue by ByronAGH** [Nek5000/NekExamples#146]
Hello,

I am a bit new on Nek5000. I have already ran some turbulent pipe DNS cases. However, I'm interested on your subroutines to compute the drag, utau, and time statistics during the simulation. When tryning to compile the case with makenek, a message appeared saying that there is not lpmax parameter in the SIZE file. Hence, I added lpmax=128. I tried to compile it again, but the following message pops up:

/home/byron/Nek5000/core/genxyz.f:692:20:

       COMMON /CTMP0/ XCV(3,2,2),VN1(3),VN2(3)
                    1
Warning: Named COMMON block ‘ctmp0’ at (1) shall be of the same size as elsewhere (240 vs 3456 bytes)
/home/byron/Nek5000/core/genxyz.f:1293:20:

       common /ctmp0/ xcb(2,2,2),ycb(2,2,2),zcb(2,2,2),w(ldw)
                    1
Warning: Named COMMON block ‘ctmp0’ at (1) shall be of the same size as elsewhere (7104 vs 3456 bytes)
/home/byron/Nek5000/core/genxyz.f:1344:20:

       common /ctmp0/ w(ldw,2),zg(3)

Is it necessary to do something with the files before compiling and running the simulation?

Thank you.

Regards,

Byron

**Comment by stgeke** [comment]
What nek version are you using? You should not mix a more recent nek examples version with an older nek version.

On 21 Aug 2019, at 01:55, ByronAGH <notifications@github.com <mailto:notifications@github.com> > wrote:

Hello,

I am a bit new on Nek5000. I have already ran some turbulent pipe DNS cases. However, I'm interested on your subroutines to compute the drag, utau, and time statistics during the simulation. When tryning to compile the case with makenek, a message appeared saying that there is not lpmax parameter in the SIZE file. Hence, I added lpmax=128. I tried to compile it again, but the following message pops up:

/home/byron/Nek5000/core/genxyz.f:692:20:


   COMMON /CTMP0/ XCV(3,2,2),VN1(3),VN2(3)
                1


Warning: Named COMMON block ‘ctmp0’ at (1) shall be of the same size as elsewhere (240 vs 3456 bytes)
/home/byron/Nek5000/core/genxyz.f:1293:20:


   common /ctmp0/ xcb(2,2,2),ycb(2,2,2),zcb(2,2,2),w(ldw)
                1


Warning: Named COMMON block ‘ctmp0’ at (1) shall be of the same size as elsewhere (7104 vs 3456 bytes)
/home/byron/Nek5000/core/genxyz.f:1344:20:


   common /ctmp0/ w(ldw,2),zg(3)


Is it necessary to do something with the files before compiling and running the simulation?

Thank you.

Regards,

Byron

**Comment by ByronAGH** [comment]
Hi Stefan,

Thanks for your repply.
I’m using Nek5000 V17 which I think is the latest release version. Should I use v19???

Cheers,

Byron

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stgeke** [comment]
The NekExamples repo version will only work with the Nek5000 repo version. If you use v17 you should use the shipped examples with the tarball.

On 21 Aug 2019, at 11:07, ByronAGH <notifications@github.com <mailto:notifications@github.com> > wrote:

Hi Stefan,

Thanks for your repply.
I’m using Nek5000 V17 which I think is the latest release version. Should I use v19???

Cheers,

Byron

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ByronAGH** [comment]
Hello Stefan,

Thank you for the clarification. For production simulations, which Nek5000 version do you recommend?

Kind Regards,

Byron Guerrero H.
byron.guerrerohinojosa@adelaide.edu.au
PhD. Candidate
School of Mechanical Engineering, ECMS
The University of Adelaide


________________________________
