### ISSUE TITLE
Allow user to set MPI ranks in test suite

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/NekExamples#15]
Currently, the parallel test cases in NekTests.py are always run with 4 MPI ranks.  We should allow the user to set the number of MPI ranks.

**Comment by maxhutch** [comment]
Could we build this generally enough that a future test could be cross-validation vs number of ranks?

**Comment by RonRahaman** [comment]
That's a great idea.  The user could provide a list of ranks and the test case would handle it accordingly. 

This would actually simplify the interfaces to the tests considerably.  Right now, each test case has four methods.  For example:
- TurbChannel.test_PnPn_Serial (1 rank)
- TurbChannel.test_PnPn_Parallel (4 ranks)
- TurbChannel.test_PnPn2_Serial (1 rank)
- TurbChannel.test_PnPn2_Parallel (4 ranks)

If we allow the user to specify a list of ranks, then we can reduce the test case methods to:
- TurbChannel.test_PnPn
- TurbChanneln.test_PnPn2
Each method would perform the cross-validation with the given list or ranks.  Or, if the list is a single value, no cross-validation would occur.

**Comment by stgeke** [comment]
Do we also run serial tests w/o MPI?

**Comment by RonRahaman** [comment]
We don't, I will add that as a separate issue.

**Comment by RonRahaman** [comment]
> Do we also run serial tests w/o MPI?

I added this issue to Nek5000/Nek5000#55

**Comment by fischer1** [comment]
Yes - I think this is important, since we advertise that we have this capability
and I use it regularly when debugging.

________________________________

**Comment by RonRahaman** [comment]
Closed in PR #20
