### ISSUE TITLE
ExtCyl: Could not find label "gmres: "

### ISSUE THREAD

**Issue by nicooff** [Nek5000/NekExamples#23]
I tried to run the automatic test for the ext_cyl case with the 'release/v16.0.0' branch. While it seems that the runs work fine, the tests fail and I get the following error message:

ValueError: Could not find label "gmres: " in logfile ".../NekExamples/ext_cyl/ext_cyl.log.1.pn_pn.parallel".  The run may have failed.

After a short investigation, it turns out that the label "gmres: " has been replaced by "gmres " (without the colon) in the logfile produced with the branch 'release/v16.0.0'.
This is not a big issue but if I fix the problem for the branch 'release/v16.0.0', the test might not work any more with the branches 'master' or 'develop'. How would you recommend to solve this issue?

**Comment by RonRahaman** [comment]
Thanks for catching this.  I fixed this in RonRahaman/NekExamples:develop and I synched it up with Nek5000/Nek5000:develop.   However, I forgot to sync RonRahaman/NekExamples:develop with NekExamples/NekExamples:master.

It gets confusing because NekTests.py is in two separate repos.

**Comment by nicooff** [comment]
Great! Thank you.
