### ISSUE TITLE
lowMach_test is out of sync with Nek5000 repo

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/NekExamples#27]
This PR
https://github.com/Nek5000/Nek5000/pull/101
introduced some necessary fixes in:
https://github.com/Nek5000/Nek5000/tree/develop/short_tests/lowMach_test

Now, the SIZE and .usr files in this repo are not up to date with the main repo.  

@stgeke

**Comment by stgeke** [comment]
Removed from examples as it is a short_test.
