### ISSUE TITLE
ExtCyl, PnPn-2 failure

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/NekExamples#44]
The ExtCyl, PnPn-2 test case fails with the following message:
```
1:     FAILURE: 1dragx: Test value 1.21392285787 exceeds target value 1.2138878 +/- 1e-05
```
The first broken commit is:
Nek5000/Nek5000@9bf13ae087531163fb2767e3f3b98308d1f61a1a

**Comment by adampep** [comment]
This error starts with build #10 corresponding to nek5000 commit 9bf13ae correcting plag initialisation in the routine extrapolating pressure in time. This certainly modifies slightly lift and drag, but the new value should be more exact, so I will make pull request modifying reference value.

**Comment by emerzari** [comment]
Adam,

It would be nice to document what the value of the drag is at the converged state before and after the modification - if any change.


On Apr 21, 2017, at 6:14 AM, Adam Peplinski <notifications@github.com<mailto:notifications@github.com>> wrote:


This error starts with build #10<https://github.com/Nek5000/NekExamples/pull/10> corresponding to nek5000 commit 9bf13ae correcting plag initialisation in the routine extrapolating pressure in time. This certainly modifies slightly lift and drag, but the new value should be more exact, so I will make pull request modifying reference value.
