### ISSUE TITLE
Fs2_StdWv, PnPn-2

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/NekExamples#50]
The Fs2_StdWv, PnPn test case fails with the following error:
```
1:     FAILURE: amp: Test value 0.1403051 exceeds target value 0.1403287 +/- 1e-06
```
Nek5000/Nek5000@f0266aaceb563af3f891a67482a0158b4033760b is the first bad commit

**Comment by stgeke** [comment]
Not suported with PnPn.
