### ISSUE TITLE
Pipe_Helix, PnPn failure

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/NekExamples#56]
The Pipe_Helix, PnPn test case fails with the following error:
```
1:     FAILURE: err2: Test value 1.9077636 exceeds target value 1.9077617 +/- 1e-06
```
Nek5000/Nek5000@54f7f9db7a51e1d2a27f7d14ce5606e7886f8460 is the first bad commit

**Comment by stgeke** [comment]
I don't thing something is wrong here, we just need to relax delta to 1e-5.
