### ISSUE TITLE
Add remaining test cases

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/NekExamples#6]
We still need to implement some test cases from the legacy test suite.  These are trickier than the others, so I've been procrastinating.  :) 
- [ ] 2d_eigtest/eig1.rea
- [x] benard/ray9.rea
- [x] benard/ray_dn.rea
- [x] benard/ray_nn.rea
- [ ] cone/cone.rea
- [ ] cone/cone016.rea
- [ ] cone/cone064.rea
- [ ] cone/cone256.rea
- [ ] eddy/amg_eddy.rea
- [ ] eddy/htps_ed.rea
- [ ] eddy_neknek/eddy_neknek.rea
- [ ] expansion/expansion.rea

**Comment by RonRahaman** [comment]
Priorities are:
2d_eigtest
expansion

**Comment by stgeke** [comment]
@RonRahaman Can you please open an issue for every missing test.

**Comment by adampep** [comment]
fixed
