### ISSUE TITLE
implementing NekTestCase.run_neknek()

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/NekExamples#61]
In #48, I introduced nekBinRun.run_neknek().  We should also implement NekTestCase.run_neknek() as a wrapper.  

cc: @kmittal2

**Comment by stgeke** [comment]
He wants to run a neknek short test so we need the same change in the Nek5000 repo.
 
-----Original message-----

**Comment by RonRahaman** [comment]
Understood.  I opened Nek5000/Nek5000#257 as a duplicate.

**Comment by RonRahaman** [comment]
On a related note, it's becoming difficult to keep NekExamples/lib synched up in both Nek5000 and NekExamples.  

My suggestion:  If NekExamples/lib is a separate repo, and is included as a submodule, it can stay synched between Nek5000 and NekExamples.   I think some of us were opposed to submodules in the past, but I think they're incredibly useful.  

Any other suggestions?
