### ISSUE TITLE
new SIZE for mhd tests Mhd_GpfB and Mhd_GpfM

### ISSUE THREAD

**Issue by adampep** [Nek5000/NekExamples#65]
mhd tests Mhd_GpfB and Mhd_GpfM use fast diagonalization method that require lfdm to be set to 1. Right now it is set to 0 by default in SIZE.inc, which be default should not be changed. We should move lfdm to SIZE for this tests

**Comment by stgeke** [comment]
Good catch! I'll move lfdm from SIZE.inc to SIZE.

**Comment by adampep** [comment]
done

**Comment by adampep** [comment]
fixed be pull request #278
