### ISSUE TITLE
expected failures

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/NekExamples#7]
A number of tests are "expected" to fail, in that they have failed in Nek5000 for some time now (dating back to the SVN repo).  

Until we fix these tests, I'd like to mark them as "expected failures" in NekTests.py using one of these decorators:
https://docs.python.org/2/library/unittest.html#skipping-tests-and-expected-failures

**Comment by maxhutch** [comment]
Great idea!

**Comment by RonRahaman** [comment]
The unittest.expectedFailure decorator breaks Twisted Trials test runner (https://twistedmatrix.com/trac/ticket/4811), which is used in buildbot.  I'd really like to maintain interoperability with buildbot, so the how should be mark the expected failures?  

I know that the unittest.skip decorator works.  This won't run the decorated test method at all, so the failure won't appear.  Is this acceptable?

**Comment by maxhutch** [comment]
Looks like the fix in Twisted Trial went stale.  `unittest.skip` seems ok for now, but can we leave this open with a `blocked externally` label or something?

**Comment by RonRahaman** [comment]
Upon consideration, I'm not satisfied with using ```unittest.skip```.  I'd like to always run the expected failures to see exactly how/why they fail.  That information is valuable.  

I think we can mark the expected failures at the level of buildbot (not at the level of unittest).  Each TestCase is run by buildbot using a [Trial](http://docs.buildbot.net/0.8.8/manual/cfg-buildsteps.html#trial) BuildStep.  Like all BuildSteps, there are [parameters](http://docs.buildbot.net/0.8.8/manual/cfg-buildsteps.html#common-parameters) can control how failures and warnings are handled.  For the TestCases that are expected failures, we can set ```flunkOnFailure=False``` and ```warnOnFailure=True```.  That way, the expected failures are still run, but  if (or rather, when) they fail, buildbot will not mark the overall build as a failure.  I think they'll also be colored yellow (instead of red) in the GUI.

What do you think?

**Comment by maxhutch** [comment]
Sounds good.  Can we also annotate them in case someone is running locally?
