### ISSUE TITLE
online documentation - small correction

### ISSUE THREAD

**Issue by fischer1** [Nek5000/NekExamples#81]
In the instructions -- it says type "ethier" ... but I guess it should be type "turbChannel" ?

cd ~
tar -xvzf Nek5000_17.0.0.tar.gz
export PATH=$HOME/Nek5000/bin:$PATH
cd ~/Nek5000/tools; ./maketools genmap
cd ~/Nek5000/run
cp -r ../examples/turbChannel .
cd turbChannel
genmap                    # run partioner, on input type ethier
makenek turbChannel       # build case, edit script to change settings
nekbmpi turbChannel 2     # run Nek5000 on 2 ranks in the background
echo -2 >ioinfo           # stop Nek5000 run and dump checkpoint
visnek turbChannel; visit -o turbChannel.nek5000 # requires a VisIt installation

**Comment by stgeke** [comment]
This has nothing to do with NekExamples. Anyway I just fixed it in the Nek5000 repo.
