### ISSUE TITLE
Where is the Kovasznay example?

### ISSUE THREAD

**Issue by fischer1** [Nek5000/NekExamples#99]

**Comment by adampep** [comment]
There are 2 kovasznay setups in Nek5000/short_tests. To avoid repetition Stefan removed them from examples (commit e35062c)

**Comment by stgeke** [comment]
Correct but then we decided to copy all short tests to examples again. Right?

-----Original message-----

**Comment by adampep** [comment]
No. You've cleaned it up after I've added all the short test. I've even added one missing kovasznay example (commit 71df276) before your clean up and it was removed. I thought we finally decided not to repeat the same piece of code number of times and and not to duplicate examples. One could add to nek repositpry description of the short tests similar to the one we have for nek examples. I could point to these examples in nekexamples readme as well.

**Comment by stgeke** [comment]
I am not sure if I understand what you are saying.

LowMach_test is a short_test _and_ an example. This is correct. Yes duplicating examples doesn't make sense but we should have a least one Kovasznay example in NekExamples. It looks like I delete it by mistake. 


-----Original message-----

**Comment by adampep** [comment]
OK. I will add it.

**Comment by adampep** [comment]
Fixed
